title: Jason Wai
logo: /images/me.jpg
description: 'privacy technology law '
baseurl: ''
url: ''
author:
  bio: 'Hi, my name is Jason.'
  name: Jason Wai
twitter: 'https://twitter.com/'
facebook: 'https://facebook.com/'
dribbble: 'https://dribbble.com/'
instagram: 'https://instagram.com/'
pinterest: 'https://pinterest.com/'
email: forexample@website.com
hero: true
hero-title: Jason Wai
hero-subtitle: Privacy. Law. Technology.
hero-image: /images/milky-way-1023340_1920.jpg
footer-image: /images/milky-way-984050_1920.jpg
disqus-identifier: mr-brown
google-analytics: ''
mailchimp: ''
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
paginate: 4
paginate_path: '/page/:num'
defaults:
  - scope:
      path: _pages
    values:
      permalink: '/:basename:output_ext'
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
include:
  - _pages
sass:
  sass_dir: _sass
  style: compressed
